### ISSUE TITLE
gxshell on ifarm can't find gxshell command

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/hd_singularity#6]
If I follow the instructions in the README for gxshell blindly, on the ifarm, I get the following error:

$ gxshell
FATAL:   "gxshell": executable file not found in $PATH

My take is that the gxshell command in not in the path within the container. If that's the case I'm not sure how to fix that.

**Comment by s6pepaul** [comment]
Are the scripts already added to the container? I haven't done it, yet. I just added the instructions here.
If yes, did you do the
    cp 10-docker2singularity.sh /.singularity.d/env/10-docker2singularity.sh
?
This should add /usr/local/bin to PATH. I thought this should be enough. If not then there are some differences between my Centos7 container and the GlueX one and I need to investigate.

**Comment by markito3** [comment]
The scripts have not been added to the container. I didn't know that that was necessary, though perhaps I should have. So the next step for me is clear now. Thanks.
